export const ERROR_CODES = {
  MODEL_ERROR: "MODEL_ERROR",
  PROCESS_ERROR: "PROCESS_ERROR",
  TIMEOUT: "TIMEOUT",
  PLAN_INVALID: "PLAN_INVALID",
  BUILD_FAILURE: "BUILD_FAILURE",
  TEST_FAILURE: "TEST_FAILURE",
  DATABASE_FAILURE: "DATABASE_FAILURE",
  ENVIRONMENT_FAILURE: "ENVIRONMENT_FAILURE",
  REVIEW_FAILURE: "REVIEW_FAILURE",
  MAX_ITERATIONS: "MAX_ITERATIONS",
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
